### ISSUE TITLE
dll с подписью

### ISSUE THREAD

**Issue by Sernyl** [skbkontur/gremit#10]
Данную библиотеку невозможно использовать в подписанных сборках, поскольку подписанные сборки должны ссылаться только на другие подписанные сборки. Мы используем formats, который у которого в зависимости flash-props boundle, который в свою очередь ссылается на GrEmit. Раньше, когда GrEmit был в цементе мы просто изменяли csproj'и и добавляли в InternalsVisibleTo соответствующий публичный ключ и после этого шла компиляция. Теперь же, когда GrEmit закачивается через NuGet, данный метод не работает, поскольку он не подписан. Нам бы хотелось, либо чтобы сборка при выкачивании из NuGet была подписана, либо чтобы для Лайта собрали отдельную подписанную сборку, которую мы будем использовать при сборке formats.

**Comment by AndrewKostousov** [comment]
Как вы в итоге зарешали свою проблему?

**Comment by Sernyl** [comment]
Подписываем dll сами через ilasm ildasm и потом билдим все остальное, что на нее ссылается.

**Comment by AndrewKostousov** [comment]
Ясно. А откуда у вас вообще требование - использовать только подписанные сборки? В их в GAC что ли устанавливаете?

**Comment by Sernyl** [comment]
Нам требуется подписывать лайт, поскольку это десктопное приложение для пользователя. А MSBuild требует чтобы все используемые сборки были подписаны. В процессе билда форматса, который в лайте используется, фигурирует GrEmit. И, собственно, сборка подписанного форматса, без подписания GrEmit не представлялась возможной. Но поскольку, как нам сказали, сам форматс не требует GrEmit в рантайме, мы решили, что сам GrEmit мы подпишем, а то на что сам GrEmit ссылается, нам не нужно.

**Comment by AndrewKostousov** [comment]
Можно было бы инсталлятор подписывать. С точки зрения гарантий безопасности, мне кажется, этого было бы вполне достаточно. Подпись же только авторство и неизменяемость бинарей дает. Если злоумышленник получит контроль над машиной пользователя после установки Лайта, самое последнее, что всех будет волновать, это неизменность dll-ек Лайта :-)

**Comment by esperantos** [comment]
Пытались делать неподписанный Лайт несколько лет назад ровно из этих соображений. Словили спецэффекты в Интеграторском интерфейсе.
Если верно помню:
ИИ Лайта торчит через COM. Проблема была в том, что в нем перестал работать механизм событий. Вроде даже находили какую-то инфу про это в MSDN. Было давно. За точность не ручаюсь.

**Comment by esperantos** [comment]
Также неподписанные сборки (а точнее процесс) имеют все шансы улететь в песочницу антивируса со всеми вытекающими.
