### ISSUE TITLE
InvalidOperationException when trying to read dynamic method body

### ISSUE THREAD

**Issue by TechInterMezzo** [skbkontur/gremit#12]
Hi,
I am trying to use the methods in MethodBodyParsing to look at the IL code of a compiled Expression.
It's failing with:

```
InvalidOperationException: Unable to set a value of type 'DynamicILInfo' to an instance of type 'DynamicILInfo'
        ldarg.0                                           // [DynamicMethod]
        ldarg.1                                           // [DynamicMethod, Object]
        castclass DynamicScope                            // [DynamicMethod, DynamicScope]
        call DynamicILInfo DynamicMethod.GetDynamicILInfo(DynamicScope)
                                                          // [DynamicILInfo]
        ret                                               // 
```

I think it's the following method:
GrEmit.MethodBodyParsing.DynamicMethodWrapper.BuildGetDynamicILInfo

My code is:

```csharp
using System;
using System.Linq.Expressions;

namespace Test
{
    static class Program
    {
        struct Test
        {
            public override string ToString()
            {
                return "12345";
            }
        }

        static void Main(string[] args)
        {

            var obj = Expression.New(typeof(Test));
            var call = Expression.Call(obj, typeof(object).GetMethod("ToString"));
            var lambda = Expression.Lambda<Func<string>>(call);
            var method = lambda.Compile();
            var instructions = GrEmit.MethodBodyParsing.MethodBody.Read(method.Method, true).Instructions;
            foreach (var inst in instructions)
            {
                Console.WriteLine(inst);
            }
        }
    }
}
```

Am I doing something wrong or is it just not working anymore with newer .NET framework versions? I know you did some magic there with internal functions but I don't want to use it for production code either way. It's just for experiments and learning.

**Comment by AndrewKostousov** [comment]
Thanks for pointing this out. IL modification related functionality had been broken when we added .NET Core support (PR #9).

I think it is better to have more focused cross-platform GrEmit package, so I will remove this code entirely. It is not needed for `GroboIL` to work anyway.

If you need these `MethodBodyParsing` features you can use older version of GrEmit package. I believe [v2.1.9](https://www.nuget.org/packages/GrEmit/2.1.9) should work fine.
