### ISSUE TITLE
IL modification in .NET Core

### ISSUE THREAD

**Issue by hongoxl** [skbkontur/gremit#17]
Hi,

Is it possible to use GroboIL to modify the IL code of a .net core application?
I am trying to use the profiling API together with GrEmit to modify certain calls from my .net core app but I don't see how to do it with GroboIL.

I have seen the example of GroboTrace but I think it only works with full framework apps.

I have also read that the MethodBodyParsing namespace has been removed in the latest versions. What problems would I encounter when using or implementing MethodBodyParsing related methods for .net core apps? It would be very hard to perform?

**Comment by AndrewKostousov** [comment]
Frankly speaking, I don't know whether it is easy/hard/impossible to implement MethodBodyParsing functionality for .NET Core. Never tried to do that. Maybe @homuroll can clarify this point...

As it was discussed in #12 issue it is better to have more focused GrEmit package anyway. So I believe that IL modification related functionality should be put in another package.
