### ISSUE TITLE
Add license info in nuget package

### ISSUE THREAD

**Issue by catdavni** [skbkontur/gremit#25]
GrEmit uses MIT license that says 
```
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
```
Would be great if you add license info (license.txt or link to license page) because it's hard to monitor license on any changes and update it manually in products that uses your library.

**Comment by Anton92nd** [comment]
License file will appear in nuget packages starting from [3.3.20](https://www.nuget.org/packages/GrEmit/3.3.20).
I hope this is what you wanted.
