### ISSUE TITLE
.net 8 error Unable to extract parameter types of 'System.Reflection.Emit.RuntimeConstructorBuilder'

### ISSUE THREAD

**Issue by MIVerTFT** [skbkontur/gremit#33]
Hi.
An error occurs when trying to emit a constructor in .net 8...

```csharp
Unhandled exception. System.NotSupportedException: Unable to extract parameter types of 'System.Reflection.Emit.RuntimeConstructorBuilder'
   at GrEmit.Utils.ReflectionExtensions.GetParameterTypes(MethodBase method)
   at GrEmit.GroboIL..ctor(ConstructorBuilder constructor, Boolean analyzeStack)
```

Apparently this is due to the fact that in .net 8, the DefineConstructor method began to return the Runtime ConstructorBuilder type, which is the descendant of ConstructorBuilder.

**Comment by qoter** [comment]
fixed in [3.5.1](https://github.com/skbkontur/gremit/releases/tag/v3.5-release)
